Inventory CRUD module
FBM-DT/FBM-DT-BE pull request #18
Opened 2023-07-01 11:42 UTC by thiengoten

2023-07-02 08:58 UTC, thanhvo041120 commented on src/modules/inventory/entities/inventory.entity.ts
> +  @ApiProperty()
Entity không cần khai báo ApiProperty của Swagger

2023-07-02 08:59 UTC, thanhvo041120 commented on src/modules/inventory/inventory.controller.ts
> +  @UsePipes(ValidationPipe)
Đã implement Validation Pipe global tại main.ts. Không cần thiết khai báo tại từng controller.

2023-07-02 09:00 UTC, thanhvo041120 commented on src/modules/inventory/inventory.controller.ts
> +  @Get()
@Get(), @Patch() nên có đường dẫn cụ thể ví dụ @Get('list') @Patch('update/:id')

2023-07-02 09:01 UTC, thanhvo041120 commented on src/modules/inventory/inventory.controller.ts
> +      const response: GetInventoryByIdResponseDto =
Nên để phần này vào service reference to MR: https://github.com/FBM-DT/FBM-DT-BE/pull/16

2023-07-02 09:01 UTC, thanhvo041120 commented on src/modules/inventory/dto/Inventory.request.dto.ts
> +  @IsNotEmpty({ message: 'The name is required' })
Nên check empty trước khi check định dạng.

2023-07-07 05:25 UTC, thanhvo041120 commented on src/modules/inventory/inventory.controller.ts
> +  @Get()
cho cả từng get lẫn delete nha e

2023-07-08 07:01 UTC, namphammati0210 requested changes

2023-07-08 07:01 UTC, namphammati0210 commented on src/modules/inventory/inventory.controller.ts
> +    response.status = 200;
Xài AppResponse nha em

2023-07-08 07:01 UTC, namphammati0210 commented on src/modules/inventory/inventory.controller.ts
> +      console.log(
xài AppResponse nha em , em liên hệ anh @thanhvo041120  nha

2023-07-12 14:35 UTC, merged