Fd 43/auth module-account module
FBM-DT/FBM-DT-BE pull request #19
Opened 2023-07-06 03:39 UTC by tuannd20

2023-07-08 05:53 UTC, namphammati0210 submitted a review, later dismissed
Check lại comments nha em

2023-07-08 05:53 UTC, namphammati0210 commented on package.json
> +    "passport-local": "^1.0.0",
Xóa passport-local

2023-07-08 05:53 UTC, namphammati0210 commented on package.json
> +    "@types/passport-local": "^1.0.35",
Xóa @types/passport-local

2023-07-08 05:53 UTC, namphammati0210 commented on src/app.module.ts
> +import { SeedService } from './seeders.service';
Xử lý seed DB bằng typeORM

2023-07-08 05:53 UTC, namphammati0210 commented on src/app.module.ts
> +import { SeedService } from './seeders.service';
Xóa SeedService

2023-07-08 05:53 UTC, namphammati0210 commented on src/app.module.ts
> +  providers: [AppService, SeedService],
Xóa SeedService

2023-07-08 05:53 UTC, namphammati0210 commented on src/core/constants/ConstValue.ts
> +export const TYPEORM = 'TYPEORM';
JWT_ACCESS_SECRET_KEY, ACCESS_EXPIRES_TIME, JWT_REFRESH_SECRET_KEY, REFRESH_EXPIRES_TIME . Đưa những key này ra .env.sample

2023-07-08 05:53 UTC, namphammati0210 commented on src/core/shared/custom.http.exception.ts
> +import { HttpException, HttpStatus } from '@nestjs/common';
Remove file này

2023-07-08 05:53 UTC, namphammati0210 commented on src/core/shared/exception.filter.ts
> +  Catch,
Xóa file

2023-07-08 05:53 UTC, namphammati0210 commented on src/db/masterData/index.ts
> +export * from './role.data';
xóa file

2023-07-08 05:53 UTC, namphammati0210 commented on src/db/masterData/role.data.ts
> +import { ACCOUNT_ROLE } from '../../core/constants';
xóa file

2023-07-08 05:53 UTC, namphammati0210 commented on src/db/masterData/user.data.ts
> +export const userData = [
Migrate dần những dummy data này qua Seed bằng TypeORM

2023-07-08 05:53 UTC, namphammati0210 commented on src/main.ts
> +  await app.listen(3001);
await app.listen(process.env.PORT, '0.0.0.0');

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/controllers/account.controller.ts
> +    response.status = 200;
Xài AppResponse trong controller

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/controllers/account.controller.ts
> +    return response;
Xài AppResponse

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/dto/account.request.dto.ts
> +import { IsInt, IsNotEmpty, IsOptional, IsString } from 'class-validator';
Đổi src/modules/auth/dto/account.request.dto.ts
=> 
auth/dto/requests/account.dto.ts

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/account.service.ts
> +  GetAccountByIdResponseDto,
Đổi GetAccountByIdResponseDto => GetAccountReqDto

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/account.service.ts
> +  UpdateAccountResponseDto,
Tương tự những Dto khác

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +import { CustomHttpException } from '../../../core/shared/custom.http.exception';
Xài AppResponse

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +  async validate(
validateAccount

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +          'The phone number or password is invalid',
tạo  constrants/errorMessages rồi đưa error message vào đó

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +      const account = Object.getOwnPropertyDescriptors(validationAccount?.data);
Note lại chỗ này với @thanhvo041120

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +        AppResponse.setUserErrorResponse<ValidateAccountResponseDto>(
Function này call nội bộ nên không cần return về AppResponse, chỉ cần value là đủ

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +  ): Promise<ValidateAccountResponseDto> {
return boolean

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +      if (account?.status?.value === 400) {
Refactor lại function này

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +      return tokens;
xài AppResponse

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +        throw error;
xài AppResponse cho chỗ này, thêm custom error message

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +  async handleLogout(payload: IAuthAccess) {
refactor tương tự với handleSignin

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +  async verifyAccessToken(token: string): Promise<Account> {
return boolean và không xài AppResponse

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/services/auth.service.ts
> +      console.log(error.message);
xóa console.log thay bằng throw exception

2023-07-08 05:53 UTC, namphammati0210 commented on src/modules/auth/strategies/refreshToken.strategy.ts
> +import { JWT_REFRESH_SECRET_KEY } from '../../../core/constants';
lấy từ env

2023-07-08 05:53 UTC, namphammati0210 commented on src/seeders.service.ts
> +  async seedUserData() {
migrate qua TypeORM

2023-07-16 04:22 UTC, thanhvo041120 requested changes

2023-07-16 04:22 UTC, thanhvo041120 commented on src/db/seeders/1689343071084-seedRole.ts
> +    await queryRunner.query('INSERT INTO ROLE(name) VALUES ($1),($2),($3)', [
thống nhất rule seeding là tên bảng viết thường và bỏ vào trong dấu "", áp dụng cho cả tên field (ex: INSERT INTO "role"("name"))

2023-07-16 04:22 UTC, thanhvo041120 commented on src/db/seeders/1689343071084-seedRole.ts
> +    await queryRunner.query('DELETE FROM ROLE WHERE name IN ($1,$2,$3)', [
Tương tự comment trên

2023-07-16 04:22 UTC, thanhvo041120 commented on src/modules/auth/constrants/errorMessages.ts
> +  THE_PHONE_NUMBER_OR_PASSWORD_IS_INVALID = 'The phone number or password is invalid',
Nên refactor để có thể dùng chung cho các service khác. Hạn chế create quá nhiều error message cụ thể cho 1 service.
Tình huống xảy ra nếu những service khác muốn dùng error message sẽ phải create nhiều enum khác nhau

2023-07-16 04:22 UTC, thanhvo041120 commented on src/modules/auth/controllers/account.controller.ts
> +  async onlyAdmin(@Req() req: Request) {
Define kiểu trả về cho từng function để người khác có thể hiểu được kiểu dữ liệu trả về khi đọc code, nếu để trống sẽ bị gán mặc định là Promise<any> hoặc any.

2023-07-16 04:22 UTC, thanhvo041120 commented on src/modules/auth/controllers/auth.controller.ts
> +    console.log(account);
xóa console.log không cần thiết

2023-07-20 15:32 UTC, thanhvo041120 requested changes

2023-07-20 15:32 UTC, thanhvo041120 commented on src/modules/auth/controllers/account.controller.ts
> +  async getAccountList() {
Add kiểu dữ liệu trả về

2023-07-20 15:32 UTC, thanhvo041120 commented on src/modules/auth/controllers/auth.controller.ts
> +    return await this.authService.handleSignin(req.body);
Nếu không cần thiết thì design DTO rồi dùng @Body @Query @Params để pass value vào API. Hạn chế sử dụng Library-specific không cần thiết.

2023-07-20 15:32 UTC, thanhvo041120 commented on src/modules/auth/services/auth.service.ts
> +      return response.refreshToken;
Nếu service trả ra frontend thì xử dụng AppRes

2023-07-22 02:48 UTC, thanhvo041120 requested changes

2023-07-22 02:48 UTC, thanhvo041120 commented on src/core/shared/common/error.ts
> +    throw new Error(`${message} is invalid`);
return error string

2023-07-23 08:15 UTC, thanhvo041120 approved these changes

2023-07-23 08:15 UTC, thanhvo041120 approved these changes

2023-07-23 08:16 UTC, merged