fix: 🐛 hotfix inventory migration
FBM-DT/FBM-DT-BE pull request #20
Opened 2023-07-15 16:30 UTC by thiengoten

fix inventory migrations doesn't work

2023-07-16 04:04 UTC, thanhvo041120 requested changes

2023-07-16 04:04 UTC, thanhvo041120 commented on src/db/migrations/1689438370020-Inventory.ts
> +        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phoneNumber"`);
Hiện tại chưa có column phoneNumber, kiểm tra lại code migration để xác nhận thay đổi tên field khi nào

2023-07-16 04:39 UTC, thiengoten commented on src/db/migrations/1689438370020-Inventory.ts
> +        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phoneNumber"`);
Em migration down hết inventory bên em r chạy lại nó generate ra cái code migrate như v a. E k đổi bên user entity mak nó ra v  a

2023-07-17 15:32 UTC, thanhvo041120 approved these changes

2023-07-17 15:36 UTC, merged